### ISSUE TITLE
server is runing but not logging into server is runing

### ISSUE THREAD

**Issue by vivek80801** [adarshaacharya/CodeTreats#12]
**Describe the bug**
server is runing but not logging into server is runing

**To Reproduce**
1. Go to **codeTreats**
2.   write this code 

```javascript

const http =require("http");

const server =http.createServer((req, res)=> {
    if (req.url === "/") {
        res.write("Hello Wrold");
        res.end();
    }
    if (req.url === "/number") {
        res.write(JSON.stringify([1, 2, 3], null, 1));
        res.end();
    }
});

server.listen(3200);

console.log("listening on port 3200...");
```

3. select Javascript as language

**Expected behavior**
Should give output `listening on port 3200...`

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS
 - Browser Chrome
 
**Additional Context"
I was trying to create local server.

**Comment by adarshaacharya** [comment]
Http interfaces aren't in support yet. The code execution part is totally dependent on [glot](https://glot.io/) so, I have to figure how to support these features by moving to next services. If you have idea then you can suggest some.

Thank you for raising issue:)
